mng/urls.py
from django.urls import path

from mng import views


app_name = 'mng'

urlpatterns = [
    path('', views.mypage, name='mypage'),
    path('add', views.add, name='add'),
    path('all_tasks', views.all_tasks, name='all_tasks'),
    path('edit/<int:task_id>', views.task_edit, name='task_edit'),
    path('edit/<int:task_id>/add_progress', views.add_progress, name='add_progress'),
    path('testing', views.testing, name='test'),
]

mytask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mng.urls')),
    path('admin/', admin.site.urls),
]

mng/models.py
from django.db import models

# Create your models here.


CONDITION_CHOICEES = (
    (1, '未着手'),
    (2, '未完了'),
    (3, '完了')
)
class task(models.Model):
    name = models.CharField(max_length=20)
    level = models.IntegerField(default=1)
    overview = models.CharField(max_length=100)
    condition = models.IntegerField(choices=CONDITION_CHOICEES,
                                    blank=True, null=True)
    add_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class progress(models.Model):
    task = models.ForeignKey(task, on_delete=models.CASCADE,blank=True, null=True)
    date = models.DateField()
    progress = models.IntegerField(default=0)
    content = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.task.name + " / " +self.date.strftime('%Y年%m月%d日')

mng/views.py
from django.shortcuts import render, get_object_or_404
from mng.models import task,progress
from .form import taskForm, progressForm
from django.utils import timezone
from mng.functions import get_progress_degree
from django.db.models import Q
from django.http import HttpResponse

# Create your views here.
display_task_number = 4

def mypage(request):

    if request.method == 'POST':
        form = taskForm(request.POST)
        if form.is_valid():
            name = request.POST['name']
            level = request.POST['level']
            overview = request.POST['overview']
            add_date = timezone.now()
            condition = 1
            t = task(name=name, level=level, overview=overview,
                     condition=condition, add_date=add_date)
            t.save()

    # 最近のタスク一覧を取得
    latest_tasks = task.objects.all().order_by("-id")[0:display_task_number]
    latest_dic = get_progress_degree(latest_tasks)

    # 未完了のタスク一覧を取得
    nocomplate_tasks = task.objects.filter(Q(condition=1) | Q(condition=2)).order_by("-id")[0:display_task_number]
    nocomplate_dic = get_progress_degree(nocomplate_tasks)

    # 完了したタスク一覧を取得
    complate_tasks = task.objects.filter(condition=3).order_by("-id")[0:display_task_number]
    complate_dic = get_progress_degree(complate_tasks)



    return render(request, 'mng/mypage.html',
                  {"latest_tasks": latest_tasks, "latest_dic": latest_dic,
                   "nocomplate_tasks": nocomplate_tasks, "nocomplate_dic": nocomplate_dic,
                   "complate_tasks": complate_tasks, "complate_dic": complate_dic}
                  )


def add(request):

    return render(request, 'mng/add.html')


def task_edit(request, task_id):

    if request.method == 'POST':

        form = progressForm(request.POST)
        if form.is_valid():
            t = task.objects.get(id=task_id)
            date = request.POST['date']
            pr = request.POST['progress']
            content = request.POST['content']

            p = progress(task=t, date=date, progress=pr, content=content)
            p.save()

    t = get_object_or_404(task, id=task_id)
    ps = progress.objects.filter(task=t)
    t_p = 0
    for p in ps:
        t_p = t_p + p.progress

    t_p_d = t_p / t.level * 100

    #状態を更新
    if t_p_d == 100.0:
        #完了状態
        t.condition = 3
        #終了日を更新
        p = progress.objects.filter(task=t).latest('date')
        t.end_date = p.date
    elif t_p_d > 0.0:
        #着手状態
        t.condition = 2
    else:
        #未着手
        t.condition = 1
    t.save()

    return render(request, 'mng/task_edit.html',
                  {"task": t, "progresses": ps, "progress": t_p_d})


def add_progress(request, task_id):

    t = get_object_or_404(task, id=task_id)
    ps = progress.objects.filter(task=t)
    current_level = 0
    for p in ps:
        current_level = current_level + p.progress

    return render(request, 'mng/add_progress.html',
                  {"task": t, "current_level":current_level})


def all_tasks(request):

    ts = task.objects.all()
    return render(request, 'mng/all_tasks.html', {"all_tasks": ts})


def testing(request):

    return render(request, 'mng/testing.html')

mng/templates/mng/add.html
{% extends 'mng/base.html' %}

{% load static %}

{% block title %}タスク追加{% endblock title %}

{% block display %}
タスク追加
{% endblock display %}

{% block lead %}
タスクを追加します
{% endblock lead %}


{% block content %}

<div class="container">
    <form action="{% url 'mng:mypage' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">タスク名</label>
            <input class="form-control" type="text" name="name" id="name">
        </div>

        <div class="form-group">
            <label for="level">レベル</label>
            <div class="input-group">
                <div class="dropdown">
                    <button type="button" class="btn btn-primary dropdown-toggle"
                            data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                        レベルの選択
                    </button>

                    <ul class="dropdown-menu">
                        <li>
                            <button type="button" class="dropdown-item" value="1">1</button>
                        </li>
                        <li>
                            <button type="button" class="dropdown-item" value="2">2</button>
                        </li>
                        <li>
                            <button type="button" class="dropdown-item" value="4">4</button>
                        </li>
                        <li>
                            <button type="button" class="dropdown-item" value="8">8</button>
                        </li>
                        <li>
                            <button type="button" class="dropdown-item" value="16">16</button>
                        </li>
                        <li>
                            <button type="button" class="dropdown-item" value="99">99</button>
                        </li>
                    </ul>
                </div>
                <input type="text" readonly="readonly" name="level" id="level" class="form-control">
            </div>
        </div>

        <div class="form-group">
            <label for="orerview">タスク概要</label>
            <textarea name="overview" id="overview" class="form-control" row="3"></textarea>
        </div>

        <div class="form-group">
            <button type="submit" id="submit-button">追加</button>
        </div>
    </form>
</div>


{% block extra_js %}
<script src="{% static 'mng/js/add.js' %}"></script>
{% endblock extra_js %}

{% endblock content %}

mng/templates/mng/add_progress.html
{% extends 'mng/base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
{% endblock extra_css %}

{% block title %}進捗情報を追加する{% endblock title %}

{% block display %}
進捗の追加
{% endblock display %}

{% block lead %}
進捗情報を追加します
{% endblock lead %}

{% block content %}
<div class="container">
    <form action="{% url 'mng:task_edit' task.id %}" method="post">
        {% csrf_token %}
        <table class="table">
            {% if task %}
            <tbody>
            <tr>
                <th scope="row">タスク名</th>
                <td><p>{{task.name}}</p></td>
            </tr>
            <tr>
                <th scope="row">レベル</th>
                <td><p id="level">{{task.level}}</p></td>
            </tr>
            <tr>
                <th scope="row">現在までの進捗</th>
                <td><p id="current_level">{{current_level}}</p></td>
            </tr>
            <tr>
                <th scope="row">本日の進捗</th>
                <td>
                    <input type="text" class="form-control" name="progress"
                           id="progress">
                </td>
            </tr>
            <tr>
                <th scope="row">日にち</th>
                <td>
                    <input type="text"
                           class="form-control" id="datetimepicker"
                           name="date"
                           data-toggle="datetimepicker"
                           data-target="#datetimepicker"/>

                </td>
            </tr>
            <tr>
                <th scope="row">内容</th>
                <td>
                    <textarea id="content" name="content" class="form-control"></textarea>
                </td>
            </tr>
            <tr>
                <th scope="row"></th>
                <td>
                    <div class="text-right">
                        <button type="submit" class="float-right"
                                id="submit-button">
                            追加
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>

            {% endif %}
        </table>

    </form>
</div>

{% block extra_js %}
<script src="{% static 'mng/js/add_progress.js' %}"></script>
{% endblock extra_js %}


{% endblock content %}

mng/templates/mng/all_tasks.html
{% extends 'mng/base.html' %}

{% load static %}

{% block title %}全てのタスクをみる{% endblock title %}

{% block display %}全タスクをみる
{% endblock display %}

{% block lead %}全てのタスクをみる
{% endblock lead %}

{% block content %}
{% if all_tasks %}
<div class="container">
    <form action="#" method="post">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">タスク名</th>
                <th scope="col">レベル</th>
                <th scope="col">状態</th>
                <th scope="col">追加日</th>
                <th scope="col">終了日</th>
                <th scope="col">概要</th>
            </tr>
            </thead>
            <tbody>
            {% for task in all_tasks %}
            <tr>
                <th scope="row"><a href="{% url 'mng:task_edit' task.id %}">
                    {{task.name}}</a></th>
                <td>{{task.level}}</td>
                <td>{{task.get_condition_display}}</td>
                <td>{{task.add_date|date:'Y年m月d日'}}</td>
                <td>{{task.end_date|date:'Y年m月d日'}}</td>
                <td>{{task.overview}}</td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </form>

</div>


{% endif %}


{% block extra_js %}{% endblock extra_js %}


{% endblock content %}

mng/templates/mng/base.html
{% load i18n static %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:'en-us'}}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'mng/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'mng/css/base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/vader/jquery-ui.min.css">
    {% block extra_css %}{% endblock extra_css %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container">

    <div class="container">
        <div class="jumbotron jumbotron-extends">
            <h1 class="display-3">
                {% block display %}{% endblock %}
            </h1>
            <p class="lead">
                {% block lead %}{% endblock %}
            </p>
        </div>
    </div>

    {% block content %}
    {% endblock content %}

    <div class="container">
        <a href="{%url 'mng:mypage' %}">
            <p class="text-right">Topへ戻る</p>
        </a>
    </div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="{% static 'mng/js/bootstrap.bundle.min.js' %}"></script>

{% block extra_js %}{% endblock extra_js %}

</body>
</html>

mng/templates/mng/mypage.html
{% extends 'mng/base.html' %}

{% load static %}

{% load lookup %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'mng/css/mypage.css' %}">
<link rel="stylesheet" href="{% static 'mng/css/jquery.circliful.css' %}">
{% endblock extra_css %}

{% block title %}マイページ{% endblock title %}

{% block display %}
タスク管理
{% endblock display %}

{% block lead %}
タスクを管理します
{% endblock lead %}

{% block content %}


<div class="container">
    <form action="{% url 'mng:add'%}" method="get">
        <button type="submit" class="btn btn-secondary">タスクを追加する</button>
    </form>
</div>
<br>
<div class="container-fluid">
    <h3 class="text-success">最近のタスク</h3>
    <!-- タスク一覧を表示 -->
    <div class="row">
        {% if latest_tasks %}
        {% for task in latest_tasks %}
        <div class="col-3">
            <a href="{% url 'mng:task_edit' task.id %}" class="text-dark">
                <div class="card">
                    {% with id=task.id %}
                    <div class="circle border-bottom" data-percent="{{ latest_dic|lookup:id }}">
                    </div>
                    {% endwith %}
                    <div class="card-body">
                        <p class="card-text text-center">{{ task.name }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

<div class="container-fluid">
    <h3 class="text-success">未完了のタスク</h3>
    <!-- タスク一覧を表示 -->
    <div class="row">
        {% if nocomplate_tasks %}
        {% for task in nocomplate_tasks %}
        <div class="col-3">
            <a href="{% url 'mng:task_edit' task.id %}" class="text-dark">
                <div class="card">
                    {% with id=task.id %}
                    <div class="circle border-bottom"
                         data-percent="{{ nocomplate_dic|lookup:id }}">
                    </div>
                    {% endwith %}
                    <div class="card-body">
                        <p class="card-text text-center">{{ task.name }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

<div class="container-fluid">
    <h3 class="text-success">完了したタスク</h3>
    <!-- タスク一覧を表示 -->
    <div class="row">
        {% if complate_tasks %}
        {% for task in complate_tasks %}
        <div class="col-3">
            <a href="{% url 'mng:task_edit' task.id %}" class="text-dark">
                <div class="card">
                    {% with id=task.id %}
                    <div class="circle border-bottom"
                         data-percent="{{ complate_dic|lookup:id }}">
                    </div>
                    {% endwith %}
                    <div class="card-body">
                        <p class="card-text text-center">{{ task.name }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
<a href="{% url 'mng:all_tasks' %}"><p class="text-right">全てのタスクをみる</p></a>


{% endblock content %}
{% block extra_js %}
<script src="{% static 'mng/js/mypage.js' %}"></script>
<script src="{% static 'mng/js/jquery.circliful.min.js' %}"></script>

{% endblock extra_js %}

mng/templates/mng/task_edit.html
{% extends 'mng/base.html' %}

{% load static %}
{% block title %}タスク編集{% endblock title %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'mng/css/task_edit.css' %}">
{% endblock extra_css%}

{% block display %}
タスク編集
{% endblock display %}

{% block lead %}
タスクを編集したり確認したりします
{% endblock lead %}


{% block content %}
<!-- 以下コンテンツ -->
<div class="container">
    <table class="table">
        {% if task %}
        <tbody>
        <tr>
            <th scope="row">タスク名</th>
            <td><p class="form-control">{{task.name}}</p></td>
        </tr>
        <tr>
            <th scope="row">レベル</th>
            <td><p class="form-control">{{task.level}}</p></td>
        </tr>
        <tr>
            <th scope="row">概要</th>
            <td><P class="form-control">{{task.overview}}</P></td>
        </tr>
        <tr>
            <th scope="row">状態</th>
            <td><p class="form-control">{{task.get_condition_display}}</p></td>
        </tr>
        <tr>
            <th scope="row">進捗度</th>
            <td><p class="form-control">{{progress}}</p></td>
        </tr>

        <tr>
            <th scope="row">追加日</th>
            <td><p class="form-control">{{task.add_date|date:'Y年m月d日'}}</p></td>
        </tr>
        <tr>
            <th scope="row">終了日</th>
            <td><p class="form-control">{{task.end_date|date:'Y年m月d日'}}</p></td>
        </tr>
        {% for p in progresses %}
        <tr>
            <th scope="row">進捗詳細{{forloop.counter}}</th>
            <td><a href="#">
                <p>{{p.date|date:'Y年m月d日'}}</p>
            </a> </td>
        </tr>

        {% endfor %}
        </tbody>
        {% endif %}
    </table>

    <a class="btn btn-primary"  href="{% url 'mng:add_progress' task.id %}">このタスクの進捗を追加する
    </a>
</div>




{% block extra_js %}
{% endblock extra_js %}

{% endblock content %}

mng/templates/mng/testing.html
{% load i18n static %}
<link rel="stylesheet" href="{% static 'mng/css/bootstrap.min.css' %}">


<h3>test2</h3>
<p>test</p>